/*
    ChibiOS - Copyright (C) 2006-2026 Giovanni Di Sirio.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/**
 * @file    xcry_vectors.h
 * @brief   XHAL Crypto test suite vectors.
 * @note    Generated by test/xcrypto/ref/xcry_gen_vectors.py, do not edit.
 */

#ifndef XCRY_VECTORS_H
#define XCRY_VECTORS_H

/**
 * @brief   Cipher vector.
 */
typedef struct {
  const char                *name;
  cry_algorithm_t           algorithm;
  size_t                    key_size;
  const uint8_t             *key;
  size_t                    iv_size;
  const uint8_t             *iv;
  size_t                    size;
  const uint8_t             *pt;
  const uint8_t             *ct;
} xcry_cipher_vector_t;

/**
 * @brief   AEAD vector.
 */
typedef struct {
  const char                *name;
  cry_algorithm_t           algorithm;
  size_t                    key_size;
  const uint8_t             *key;
  size_t                    nonce_size;
  const uint8_t             *nonce;
  size_t                    aad_size;
  const uint8_t             *aad;
  size_t                    size;
  const uint8_t             *pt;
  const uint8_t             *ct;
  size_t                    tag_size;
  const uint8_t             *tag;
} xcry_aead_vector_t;

/**
 * @brief   MAC vector.
 */
typedef struct {
  const char                *name;
  cry_algorithm_t           algorithm;
  size_t                    key_size;
  const uint8_t             *key;
  size_t                    size;
  const uint8_t             *msg;
  size_t                    tag_size;
  const uint8_t             *tag;
} xcry_mac_vector_t;

/**
 * @brief   Hash vector, a NULL message is generated by the test.
 */
typedef struct {
  const char                *name;
  cry_algorithm_t           algorithm;
  size_t                    size;
  const uint8_t             *msg;
  size_t                    digest_size;
  const uint8_t             *digest;
} xcry_hash_vector_t;

/**
 * @brief   Key derivation vector.
 */
typedef struct {
  const char                *name;
  cry_algorithm_t           algorithm;
  size_t                    ikm_size;
  const uint8_t             *ikm;
  size_t                    salt_size;
  const uint8_t             *salt;
  size_t                    info_size;
  const uint8_t             *info;
  size_t                    size;
  const uint8_t             *okm;
} xcry_kdf_vector_t;

extern const xcry_cipher_vector_t xcry_aes_ecb_vectors[3];
#define XCRY_AES_ECB_VECTORS_COUNT 3U
extern const xcry_cipher_vector_t xcry_aes_ecb_long[1];
#define XCRY_AES_ECB_LONG_COUNT 1U
extern const xcry_cipher_vector_t xcry_aes_cbc_vectors[3];
#define XCRY_AES_CBC_VECTORS_COUNT 3U
extern const xcry_cipher_vector_t xcry_aes_cbc_long[1];
#define XCRY_AES_CBC_LONG_COUNT 1U
extern const xcry_cipher_vector_t xcry_aes_cfb128_vectors[3];
#define XCRY_AES_CFB128_VECTORS_COUNT 3U
extern const xcry_cipher_vector_t xcry_aes_cfb128_long[1];
#define XCRY_AES_CFB128_LONG_COUNT 1U
extern const xcry_cipher_vector_t xcry_aes_ctr_vectors[3];
#define XCRY_AES_CTR_VECTORS_COUNT 3U
extern const xcry_cipher_vector_t xcry_aes_ctr_long[1];
#define XCRY_AES_CTR_LONG_COUNT 1U
extern const xcry_aead_vector_t xcry_aes_gcm_vectors[4];
#define XCRY_AES_GCM_VECTORS_COUNT 4U
extern const xcry_aead_vector_t xcry_aes_gcm_long[1];
#define XCRY_AES_GCM_LONG_COUNT 1U
extern const xcry_aead_vector_t xcry_aes_ccm_vectors[3];
#define XCRY_AES_CCM_VECTORS_COUNT 3U
extern const xcry_mac_vector_t xcry_aes_cmac_vectors[12];
#define XCRY_AES_CMAC_VECTORS_COUNT 12U
extern const xcry_mac_vector_t xcry_hmac_vectors[18];
#define XCRY_HMAC_VECTORS_COUNT 18U
extern const xcry_hash_vector_t xcry_sha_vectors[20];
#define XCRY_SHA_VECTORS_COUNT 20U
extern const xcry_hash_vector_t xcry_sha_million_a[5];
#define XCRY_SHA_MILLION_A_COUNT 5U
extern const xcry_kdf_vector_t xcry_hkdf_vectors[3];
#define XCRY_HKDF_VECTORS_COUNT 3U

#endif /* XCRY_VECTORS_H */
