/*
    Generated by tools/mkromfs/mkromfs.py. Do not edit manually.
*/

#ifndef BIN_ROMFS_H
#define BIN_ROMFS_H

#include "vfs.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const vfs_romfs_tree_t bin_romfs;

#ifdef __cplusplus
}
#endif

#endif /* BIN_ROMFS_H */
