##############################################################################
# VFS test build wrapper.

.PHONY: all clean test

all clean test:
	$(MAKE) --no-print-directory -C testbuild $@

##############################################################################
